server:
  port: 1234
  
spring:
  application:
    name: leadingTruck
  datasource:
    url: jdbc:h2:mem:truckdb
    driver-class-name: org.h2.Driver
    username: sa
    password: local
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka